version: '3.3'
services:
  book-store:
    build:
      context: .
    networks:
      - docker-net
    restart: always
    ports:
      - ${TOMCAT_PORT:-9098}:9098

networks:
  docker-net:
    external: true