apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-store
  labels:
    app: book-store
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: book-store
  template:
    metadata:
      labels:
        app: book-store
    spec:
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
{{- end }}
      containers:
        - name: book-store
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: book-store-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: book-store-secret
                  key: POSTGRES_PASSWORD
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: book-store-secret
                  key: KEYCLOAK_CLIENT_SECRET
