apiVersion: v1
kind: Secret
metadata:
  name: book-store-secret
type: Opaque
stringData:
  KEYCLOAK_CLIENT_SECRET: "{{ .Values.secret.KEYCLOAK_CLIENT_SECRET }}"
  POSTGRES_PASSWORD: "{{ .Values.secret.POSTGRES_PASSWORD }}"