replicaCount: 1

image:
  repository: reg.sepidan.net/sepidan/book-store
  tag: 1.0.3
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 9098

env:
  TOMCAT_PORT: "9098"
  KEYCLOAK_URL: "http://localhost:9090"
  KEYCLOAK_REALM: "sepidan"
  KEYCLOAK_CLIENT_ID: "book-store"
  POSTGRES_HOST: "localhost"
  POSTGRES_DATABASE: "book-store"
  POSTGRES_USER: "db_user"
  SPRING_PROFILES_ACTIVE: "dev"

secret:
  KEYCLOAK_CLIENT_SECRET: "hxweayCjTaxakJr5UyfXDdUarUeDicje"
  POSTGRES_PASSWORD: "very_secret"